### ISSUE TITLE
raw data upload

### ISSUE THREAD

**Issue by bettydodo** [gaarangoa/MetaStorm#1]
An HTTP error "uplosd URL might be wrong or doesn't exist." kept coming out when I tried to upload raw files to a project.

**Comment by gaarangoa** [comment]
The issue should be fixed now, so you would be able to submit raw data, please, let me know if you find any issues. 

Thanks

**Comment by bettydodo** [comment]
Indeed the issue has been fixed now. 
Thank you very much!

**Comment by MatanSlutzkin** [comment]
I am experiencing the same problem.
