### ISSUE TITLE
Problem with MetaStrom in Mac in Chrome

### ISSUE THREAD

**Issue by mghanbari** [gaarangoa/MetaStorm#1]
Hi
I tried to start analysis on three metagenome samples by using MetaStrom but it seems that it does not work properly in Chrome in Mac. I uploaded the data but could not see any information in Samples part even when I added the information to metadata part. 
Any idea what is wrong?

**Comment by gaarangoa** [comment]
Hi, 

If the samples were correctly uploaded, you need to go to "Run Analysis" tab, click on "Refresh" and check whether your fastq.gz files are there or not by clicking on the arrows under the FastQ1 or FastQ2 columns in the table. 

The metadata section is designed to add the features of each sample, so, you need to select the raw files under the "Run Analysis" tab. Please check the documentation under the main page. 

Also, please check the extension of your files. MetaStorm requires gz compressed files (*.fasq.gz). For testing purpose, you can submit the example files placed here: http://bench.cs.vt.edu/Projects/Metagenome.tar.gz 

If the error persists, please let us know. 

Regards

**Comment by mghanbari** [comment]
Thank you for  the reply. Actually, I uploaded the data from the example you sent. Still no success. When I click on Refresh in run Analysis part, nothing happens. I attached the pics of the procedure that I followed. The first file is how the uploading step looks like and  the second is the Run Analysis section. Any idea?
<img width="1211" alt="screen shot 2016-10-02 at 18 53 28" src="https://cloud.githubusercontent.com/assets/10992636/19022155/90ffbf72-88d1-11e6-9c48-3c5ccd1c81d5.png">
<img width="1254" alt="screen shot 2016-10-02 at 19 00 17" src="https://cloud.githubusercontent.com/assets/10992636/19022164/a61687c4-88d1-11e6-9b91-b18525114632.png">

**Comment by gaarangoa** [comment]
did you fill up the Metadata?, you need to add the metadata for each sample before running the analysis. Go to "Setup Metadata" First enter the number of samples, then "Go", then, fill up the form and click on submit. After, go to the "Run Analysis" tab and click refresh, you should be able to see the sample in the table to choose the raw reads. 

If those steps don't work, please send us an email to cmetagen@gmail.com with your project name, so, we can check our logs. 

Thanks
