### ISSUE TITLE
MetaStorm upload error HTTP Error.  Upload URL might be wrong or doesn't exist. "HTTP Error.  Upload URL might be wrong or doesn't exist".

### ISSUE THREAD

**Issue by MatanSlutzkin** [gaarangoa/MetaStorm#2]
I am a relatively new MetaStorm user and I have recently been getting this upload error: HTTP Error. 
Upload URL might be wrong or doesn't exist.
HTTP Error. 
Upload URL might be wrong or doesn't exist.
What should I do to fix this?

**Comment by gaarangoa** [comment]
Hi, 
We recently added the https:// domain to MetaStorm, so, it now serves over HTTPS not HTTP. 

To solve the issue, just reload the page. To make sure it works just force reload using ctrl+shift+r

Let me know if it works. Also, for future questions or issues, just open or post the issue in our ARGminer platform https://bench.cs.vt.edu/argminer/#/forum :)
