### ISSUE TITLE
sample & raw data didn't match

### ISSUE THREAD

**Issue by wn835166087** [gaarangoa/MetaStorm#3]
Hi,

I am trying to use metastorm.
I've uploaded the raw file and set up the metadata. But the raw data didn't match the metadata. I mean, the name of the raw data is the same as the one in meta data file, but in the 'sample' page, the FastQ1 and FastQ2 are empty..
<img width="1058" alt="2018-11-11 10 07 20" src="https://user-images.githubusercontent.com/44331857/48316564-4c24bb00-e59a-11e8-98ed-873cc9787e7d.png">
<img width="1065" alt="2018-11-11 10 07 29" src="https://user-images.githubusercontent.com/44331857/48316568-4fb84200-e59a-11e8-9d61-d2f373c10fe4.png">
<img width="933" alt="2018-11-11 10 07 36" src="https://user-images.githubusercontent.com/44331857/48316570-547cf600-e59a-11e8-9f4d-22c004fb546f.png">
<img width="344" alt="2018-11-11 10 07 43" src="https://user-images.githubusercontent.com/44331857/48316573-56df5000-e59a-11e8-8e89-5e470cbdd0f3.png">
I've also tried to tap in the 'sample' page manually the name of raw data, but it didn't work as well.

Thank you very much!

**Comment by gaarangoa** [comment]
Hi, 
We had a storage issue few days ago and that's probably why your files are not showing up. Can you please submit your samples again and let me know if they go through?

Thanks
