### ISSUE TITLE
Issue displaying tables

### ISSUE THREAD

**Issue by zblara** [gaarangoa/MetaStorm#6]
Hello! 

I highly appreciate the devs' work on this webserver. The objectives are exactly in accordance with my research so I hope to be able to use MetaStorm successfully.

I would just like to bring up this issue with viewing samples on the project Sample page since I get the following error message "_The license key for Handsontable is missing. Use your purchased key to activate the product. Alternatively, you can activate Handsontable to use for non-commercial purposes by passing the key: 'non-commercial-and-evaluation'_." (see picture below) 
![image](https://user-images.githubusercontent.com/72982331/131817717-bbc5c27d-927b-4885-b24d-e4a1a4091fc1.png)

I have tried this with raw fq.gz files and assembly fasta files. I'm sure that the files are successfully uploaded but when I try to view other tabs, they are missing. Any insight from the devs would be highly appreciated.

Many thanks,
Zach

**Comment by gaarangoa** [comment]
This error has been solved and now there should not be any message from hands on table.
